name: Release & Notify Packagist

on:
  release:
    types: [published]  # release-please가 머지되며 GitHub Release 생성 시 작동

jobs:
  notify-packagist:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Packagist
        run: |
          curl -X POST https://packagist.org/api/update-package \
            -H 'Content-Type: application/json' \
            -d '{
              "username": "${{ secrets.PACKAGIST_USERNAME }}",
              "apiToken": "${{ secrets.PACKAGIST_TOKEN }}"
            }'